[package]
name = "mir_codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
ast_model = { version = "0.1.0", path = "../../soul_ast/ast_model" }
mir_model = { version = "0.1.0", path = "../mir_model" }
soul_utils = { version = "0.1.0", path = "../../soul_utils" }
inkwell = { version = "0.5", features = ["llvm16-0"] }
anyhow = "1"

[dev-dependencies]
ast_parser = { version = "0.1.0", path = "../../soul_ast/ast_parser" }
ast_run = { version = "0.1.0", path = "../../soul_ast/ast_run" }
mir_parser = { version = "0.1.0", path = "../mir_parser" }
mir_run = { version = "0.1.0", path = "../mir_run" }
soul_name_resolver = { version = "0.1.0", path = "../../soul_ast/soul_name_resolver" }
soul_tokenizer = { version = "0.1.0", path = "../../soul_tokenizer" }
